{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "15be6957",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting package metadata (current_repodata.json): done\n",
      "Solving environment: done\n",
      "\n",
      "\n",
      "==> WARNING: A newer version of conda exists. <==\n",
      "  current version: 4.10.3\n",
      "  latest version: 4.11.0\n",
      "\n",
      "Please update conda by running\n",
      "\n",
      "    $ conda update -n base -c defaults conda\n",
      "\n",
      "\n",
      "\n",
      "## Package Plan ##\n",
      "\n",
      "  environment location: /Users/young/opt/anaconda3/envs/GPT_BERT_book\n",
      "\n",
      "  added / updated specs:\n",
      "    - pytorch\n",
      "    - torchvision\n",
      "\n",
      "\n",
      "The following NEW packages will be INSTALLED:\n",
      "\n",
      "  blas               pkgs/main/osx-64::blas-1.0-mkl\n",
      "  bzip2              pkgs/main/osx-64::bzip2-1.0.8-h1de35cc_0\n",
      "  ffmpeg             pytorch/osx-64::ffmpeg-4.3-h0a44026_0\n",
      "  freetype           pkgs/main/osx-64::freetype-2.11.0-hd8bbffd_0\n",
      "  gettext            pkgs/main/osx-64::gettext-0.21.0-h7535e17_0\n",
      "  giflib             pkgs/main/osx-64::giflib-5.2.1-haf1e3a3_0\n",
      "  gmp                pkgs/main/osx-64::gmp-6.2.1-h23ab428_2\n",
      "  gnutls             pkgs/main/osx-64::gnutls-3.6.15-hed9c0bf_0\n",
      "  icu                pkgs/main/osx-64::icu-58.2-h0a44026_3\n",
      "  intel-openmp       pkgs/main/osx-64::intel-openmp-2021.4.0-hecd8cb5_3538\n",
      "  jpeg               pkgs/main/osx-64::jpeg-9d-h9ed2024_0\n",
      "  lame               pkgs/main/osx-64::lame-3.100-h1de35cc_0\n",
      "  lcms2              pkgs/main/osx-64::lcms2-2.12-hf1fd2bf_0\n",
      "  libiconv           pkgs/main/osx-64::libiconv-1.16-h1de35cc_0\n",
      "  libidn2            pkgs/main/osx-64::libidn2-2.3.2-h9ed2024_0\n",
      "  libpng             pkgs/main/osx-64::libpng-1.6.37-ha441bb4_0\n",
      "  libtasn1           pkgs/main/osx-64::libtasn1-4.16.0-h9ed2024_0\n",
      "  libtiff            pkgs/main/osx-64::libtiff-4.2.0-h87d7836_0\n",
      "  libunistring       pkgs/main/osx-64::libunistring-0.9.10-h9ed2024_0\n",
      "  libuv              pkgs/main/osx-64::libuv-1.40.0-haf1e3a3_0\n",
      "  libwebp            pkgs/main/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  libwebp-base       pkgs/main/osx-64::libwebp-base-1.2.0-h9ed2024_0\n",
      "  libxml2            pkgs/main/osx-64::libxml2-2.9.12-hcdb78fc_0\n",
      "  llvm-openmp        pkgs/main/osx-64::llvm-openmp-12.0.0-h0dcd299_1\n",
      "  lz4-c              pkgs/main/osx-64::lz4-c-1.9.3-h23ab428_1\n",
      "  mkl                pkgs/main/osx-64::mkl-2021.4.0-hecd8cb5_637\n",
      "  mkl-service        pkgs/main/osx-64::mkl-service-2.4.0-py39h9ed2024_0\n",
      "  mkl_fft            pkgs/main/osx-64::mkl_fft-1.3.1-py39h4ab4a9b_0\n",
      "  mkl_random         pkgs/main/osx-64::mkl_random-1.2.2-py39hb2f4e1b_0\n",
      "  nettle             pkgs/main/osx-64::nettle-3.7.3-h230ac6f_1\n",
      "  numpy              pkgs/main/osx-64::numpy-1.21.2-py39h4b4dc7a_0\n",
      "  numpy-base         pkgs/main/osx-64::numpy-base-1.21.2-py39he0bd621_0\n",
      "  olefile            pkgs/main/noarch::olefile-0.46-pyhd3eb1b0_0\n",
      "  openh264           pkgs/main/osx-64::openh264-2.1.1-h8346a28_0\n",
      "  pillow             pkgs/main/osx-64::pillow-8.4.0-py39h98e4679_0\n",
      "  pytorch            pytorch/osx-64::pytorch-1.10.2-py3.9_0\n",
      "  torchvision        pytorch/osx-64::torchvision-0.11.3-py39_cpu\n",
      "  typing_extensions  pkgs/main/noarch::typing_extensions-3.10.0.2-pyh06a4308_0\n",
      "  zstd               pkgs/main/osx-64::zstd-1.4.9-h322a384_0\n",
      "\n",
      "\n",
      "Preparing transaction: done\n",
      "Verifying transaction: failed\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/alphaindex.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/appendable.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/basictz.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/brkiter.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/bytestream.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/bytestrie.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/bytestriebuilder.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/calendar.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/caniter.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/chariter.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/choicfmt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/coleitr.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/coll.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/compactdecimalformat.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/curramt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/currpinf.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/currunit.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/datefmt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/dbbi.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/dcfmtsym.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/decimfmt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/docmain.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/dtfmtsym.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/dtintrv.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/dtitvfmt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/dtitvinf.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/dtptngen.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/dtrule.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/enumset.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/errorcode.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/fieldpos.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/filteredbrk.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/fmtable.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/format.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/fpositer.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/gender.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/gregocal.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/icudataver.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/icuplug.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/idna.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/listformatter.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/localpointer.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/locdspnm.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/locid.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/measfmt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/measunit.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/measure.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/messagepattern.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/msgfmt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/normalizer2.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/normlzr.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/numfmt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/numsys.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/parseerr.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/parsepos.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/platform.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/plurfmt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/plurrule.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ptypes.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/putil.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/rbbi.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/rbnf.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/rbtz.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/regex.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/region.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/reldatefmt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/rep.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/resbund.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/schriter.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/scientificnumberformatter.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/search.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/selfmt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/simpleformatter.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/simpletz.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/smpdtfmt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/sortkey.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/std_string.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/strenum.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/stringpiece.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/stringtriebuilder.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/stsearch.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/symtable.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/tblcoll.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/timezone.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/tmunit.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/tmutamt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/tmutfmt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/translit.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/tzfmt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/tznames.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/tzrule.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/tztrans.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ubidi.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ubiditransform.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ubrk.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ucal.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ucasemap.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ucat.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uchar.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ucharstrie.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ucharstriebuilder.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uchriter.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uclean.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ucnv.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ucnv_cb.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ucnv_err.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ucnvsel.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ucol.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ucoleitr.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uconfig.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ucsdet.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ucurr.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/udat.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/udata.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/udateintervalformat.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/udatpg.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/udisplaycontext.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uenum.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ufieldpositer.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uformattable.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ugender.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uidna.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uiter.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uldnames.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ulistformatter.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uloc.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ulocdata.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/umachine.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/umisc.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/umsg.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/unifilt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/unifunct.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/unimatch.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/unirepl.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uniset.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/unistr.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/unorm.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/unorm2.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/unum.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/unumsys.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uobject.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/upluralrules.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uregex.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uregion.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ureldatefmt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/urename.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/urep.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ures.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uscript.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/usearch.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uset.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/usetiter.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ushape.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uspoof.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/usprep.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ustdio.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ustream.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ustring.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/ustringtrie.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/utext.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/utf.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/utf16.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/utf32.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/utf8.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/utf_old.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/utmscale.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/utrace.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/utrans.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/utypes.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uvernum.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/uversion.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'include/unicode/vtzone.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'share/icu/58.2/LICENSE'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'share/icu/58.2/config/mh-darwin'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'share/icu/58.2/install-sh'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for icu located at /Users/young/opt/anaconda3/pkgs/icu-58.2-h0a44026_3\n",
      "appears to be corrupted. The path 'share/icu/58.2/mkinstalldirs'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for lame located at /Users/young/opt/anaconda3/pkgs/lame-3.100-h1de35cc_0\n",
      "appears to be corrupted. The path 'include/lame/lame.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for lame located at /Users/young/opt/anaconda3/pkgs/lame-3.100-h1de35cc_0\n",
      "appears to be corrupted. The path 'share/doc/lame/html/about.html'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for lame located at /Users/young/opt/anaconda3/pkgs/lame-3.100-h1de35cc_0\n",
      "appears to be corrupted. The path 'share/doc/lame/html/abr.html'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for lame located at /Users/young/opt/anaconda3/pkgs/lame-3.100-h1de35cc_0\n",
      "appears to be corrupted. The path 'share/doc/lame/html/cbr.html'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for lame located at /Users/young/opt/anaconda3/pkgs/lame-3.100-h1de35cc_0\n",
      "appears to be corrupted. The path 'share/doc/lame/html/contact.html'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for lame located at /Users/young/opt/anaconda3/pkgs/lame-3.100-h1de35cc_0\n",
      "appears to be corrupted. The path 'share/doc/lame/html/contributors.html'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for lame located at /Users/young/opt/anaconda3/pkgs/lame-3.100-h1de35cc_0\n",
      "appears to be corrupted. The path 'share/doc/lame/html/detailed.html'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for lame located at /Users/young/opt/anaconda3/pkgs/lame-3.100-h1de35cc_0\n",
      "appears to be corrupted. The path 'share/doc/lame/html/history.html'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for lame located at /Users/young/opt/anaconda3/pkgs/lame-3.100-h1de35cc_0\n",
      "appears to be corrupted. The path 'share/doc/lame/html/index.html'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for lame located at /Users/young/opt/anaconda3/pkgs/lame-3.100-h1de35cc_0\n",
      "appears to be corrupted. The path 'share/doc/lame/html/introduction.html'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for lame located at /Users/young/opt/anaconda3/pkgs/lame-3.100-h1de35cc_0\n",
      "appears to be corrupted. The path 'share/doc/lame/html/links.html'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for lame located at /Users/young/opt/anaconda3/pkgs/lame-3.100-h1de35cc_0\n",
      "appears to be corrupted. The path 'share/doc/lame/html/list.html'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for lame located at /Users/young/opt/anaconda3/pkgs/lame-3.100-h1de35cc_0\n",
      "appears to be corrupted. The path 'share/doc/lame/html/ms_stereo.html'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for lame located at /Users/young/opt/anaconda3/pkgs/lame-3.100-h1de35cc_0\n",
      "appears to be corrupted. The path 'share/doc/lame/html/usage.html'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for lame located at /Users/young/opt/anaconda3/pkgs/lame-3.100-h1de35cc_0\n",
      "appears to be corrupted. The path 'share/doc/lame/html/vbr.html'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/ac3_parser.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/adts_parser.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/avcodec.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/avdct.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/avfft.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/bsf.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/codec.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/codec_desc.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/codec_id.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/codec_par.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/d3d11va.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/dirac.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/dv_profile.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/dxva2.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/jni.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/mediacodec.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/packet.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/qsv.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/vaapi.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/vdpau.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/version.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/videotoolbox.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/vorbis_parser.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavcodec/xvmc.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavfilter/avfilter.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavfilter/buffersink.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavfilter/buffersrc.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavfilter/version.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavformat/avformat.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavformat/avio.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavformat/version.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavresample/avresample.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavresample/version.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/adler32.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/aes.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/aes_ctr.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/attributes.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/audio_fifo.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/avassert.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/avconfig.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/avstring.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/avutil.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/base64.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/blowfish.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/bprint.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/bswap.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/buffer.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/camellia.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/cast5.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/channel_layout.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/common.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/cpu.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/crc.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/des.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/dict.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/display.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/dovi_meta.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/downmix_info.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/encryption_info.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/error.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/eval.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/ffversion.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/fifo.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/file.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/frame.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/hash.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/hdr_dynamic_metadata.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/hmac.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/hwcontext.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/hwcontext_cuda.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/hwcontext_d3d11va.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/hwcontext_drm.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/hwcontext_dxva2.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/hwcontext_mediacodec.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/hwcontext_opencl.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/hwcontext_qsv.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/hwcontext_vaapi.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/hwcontext_vdpau.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/hwcontext_videotoolbox.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/hwcontext_vulkan.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/imgutils.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/intfloat.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/intreadwrite.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/lfg.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/log.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/lzo.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/macros.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/mastering_display_metadata.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/mathematics.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/md5.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/mem.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/motion_vector.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/murmur3.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/opt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/parseutils.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/pixdesc.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/pixelutils.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/pixfmt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/random_seed.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/rational.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/rc4.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/replaygain.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/ripemd.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/samplefmt.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/sha.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/sha512.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/spherical.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/stereo3d.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/tea.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/threadmessage.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/time.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/timecode.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/timestamp.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/tree.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/twofish.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/tx.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/version.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/video_enc_params.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libavutil/xtea.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libswresample/swresample.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'include/libswresample/version.h'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/Makefile'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/README'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/avio_list_dir.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/avio_reading.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/decode_audio.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/decode_video.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/demuxing_decoding.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/encode_audio.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/encode_video.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/extract_mvs.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/filter_audio.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/filtering_audio.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/filtering_video.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/http_multiclient.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/hw_decode.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/metadata.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/muxing.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/qsvdec.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/remuxing.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/resampling_audio.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/scaling_video.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/transcode_aac.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/transcoding.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/vaapi_encode.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/examples/vaapi_transcode.c'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/ffprobe.xsd'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/libvpx-1080p.ffpreset'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/libvpx-1080p50_60.ffpreset'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/libvpx-360p.ffpreset'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/libvpx-720p.ffpreset'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "CondaVerificationError: The package for ffmpeg located at /Users/young/opt/anaconda3/pkgs/ffmpeg-4.3-h0a44026_0\n",
      "appears to be corrupted. The path 'share/ffmpeg/libvpx-720p50_60.ffpreset'\n",
      "specified in the package manifest cannot be found.\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::intel-openmp-2021.4.0-hecd8cb5_3538, defaults/osx-64::llvm-openmp-12.0.0-h0dcd299_1\n",
      "  path: 'lib/libiomp5.dylib'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'bin/webpinfo'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'bin/webpmux'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'include/webp/decode.h'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'include/webp/encode.h'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'include/webp/mux.h'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'include/webp/mux_types.h'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'include/webp/types.h'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'lib/libwebp.7.dylib'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'lib/libwebp.a'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'lib/libwebp.dylib'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'lib/libwebpdecoder.3.dylib'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'lib/libwebpdecoder.a'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'lib/libwebpdecoder.dylib'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'lib/libwebpmux.3.dylib'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'lib/libwebpmux.a'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'lib/libwebpmux.dylib'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'lib/pkgconfig/libwebp.pc'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'lib/pkgconfig/libwebpdecoder.pc'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'lib/pkgconfig/libwebpmux.pc'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'share/man/man1/cwebp.1'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'share/man/man1/dwebp.1'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'share/man/man1/webpinfo.1'\n",
      "\n",
      "\n",
      "ClobberError: This transaction has incompatible packages due to a shared path.\n",
      "  packages: defaults/osx-64::libwebp-base-1.2.0-h9ed2024_0, defaults/osx-64::libwebp-1.2.0-hacca55c_0\n",
      "  path: 'share/man/man1/webpmux.1'\n",
      "\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "conda install pytorch torchvision -c pytorch"
   ]
  },
  {
   "cell_type": "raw",
   "id": "0a8f208d",
   "metadata": {},
   "source": [
    "파이토치로 행렬들 정의"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "a267efa0",
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "\n",
    "x = torch.tensor([\n",
    "  [1.0, 0.0, 1.0, 0.0],\n",
    "  [0.0, 2.0, 0.0, 2.0],\n",
    "  [1.0, 1.0, 1.0, 1.0],  \n",
    "])\n",
    "w_query = torch.tensor([\n",
    "  [1.0, 0.0, 1.0],\n",
    "  [1.0, 0.0, 0.0],\n",
    "  [0.0, 0.0, 1.0],\n",
    "  [0.0, 1.0, 1.0]\n",
    "])\n",
    "w_key = torch.tensor([\n",
    "  [0.0, 0.0, 1.0],\n",
    "  [1.0, 1.0, 0.0],\n",
    "  [0.0, 1.0, 0.0],\n",
    "  [1.0, 1.0, 0.0]\n",
    "])\n",
    "w_value = torch.tensor([\n",
    "  [0.0, 2.0, 0.0],\n",
    "  [0.0, 3.0, 0.0],\n",
    "  [1.0, 0.0, 3.0],\n",
    "  [1.0, 1.0, 0.0]\n",
    "])"
   ]
  },
  {
   "cell_type": "raw",
   "id": "51c10464",
   "metadata": {},
   "source": [
    "벡터 시퀀스로 쿼리, 키, 밸류 벡터들을 만드는 부분\n",
    "torch.matmul => 행렬곱을 수행하는 함수"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "0a526741",
   "metadata": {},
   "outputs": [],
   "source": [
    "keys = torch.matmul(x, w_key)\n",
    "querys = torch.matmul(x, w_query)\n",
    "values = torch.matmul(x, w_value)"
   ]
  },
  {
   "cell_type": "raw",
   "id": "3f1ddd99",
   "metadata": {},
   "source": [
    "어텐션 스코어 만들기"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "841f7b52",
   "metadata": {},
   "outputs": [],
   "source": [
    "attn_scores = torch.matmul(querys, keys.T)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "6c614f12",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "tensor([[ 2.,  4.,  4.],\n",
       "        [ 4., 16., 12.],\n",
       "        [ 4., 12., 10.]])"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "attn_scores"
   ]
  },
  {
   "cell_type": "raw",
   "id": "8ab4160a",
   "metadata": {},
   "source": [
    "소프트맥스 확률값 만들기\n",
    "\n",
    "앞 코드 결과에, 키 벡터의 차원수 제곱근으로 나눈후 -> 소프트맥스 취함"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "fd6cd51a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "from torch.nn.functional import softmax\n",
    "\n",
    "key_dim_sqrt = np.sqrt(keys.shape[-1]) # 키 벡터 차원수?\n",
    "attn_scores_softmax = softmax(attn_scores / key_dim_sqrt, dim=-1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "6d6a8c9c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "tensor([[1.3613e-01, 4.3194e-01, 4.3194e-01],\n",
       "        [8.9045e-04, 9.0884e-01, 9.0267e-02],\n",
       "        [7.4449e-03, 7.5471e-01, 2.3785e-01]])"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "attn_scores_softmax"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d9ecdc0d",
   "metadata": {},
   "source": [
    "소프트맥스 확률과 밸류를 가중합하기"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "66fef267",
   "metadata": {},
   "outputs": [],
   "source": [
    "weighted_values = torch.matmul(attn_scores_softmax, values)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "2e556f2f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "tensor([[1.8639, 6.3194, 1.7042],\n",
       "        [1.9991, 7.8141, 0.2735],\n",
       "        [1.9926, 7.4796, 0.7359]])"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "weighted_values"
   ]
  },
  {
   "cell_type": "raw",
   "id": "6a14b6d9",
   "metadata": {},
   "source": [
    "=> 셀프 어텐션의 학습 대상: 쿼리, 키, 밸류를 만드는 가중치 행렬 (Wq, Wk, Wv)\n",
    "    코드예시 : w_query, w_key, w_value\n",
    "        => 태스크를 가장 잘 수행하는 방향으로 학습 과정에서 업데이트 됨"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "efed6cfd",
   "metadata": {},
   "source": [
    "피드포워드 뉴럴 네트워크 계산 예시\n",
    "\n",
    "기본 값들 설정"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "9836a352",
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "x = torch.tensor([2,1])\n",
    "w1 = torch.tensor([[3,2,-4],[2,-3,1]])\n",
    "b1 = 1\n",
    "w2 = torch.tensor([[-1, 1], [1,2], [3,1]])\n",
    "b2 = -1"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3bc9bdaf",
   "metadata": {},
   "source": [
    "실제 계산 수행하는 코드"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "ce261254",
   "metadata": {},
   "outputs": [],
   "source": [
    "h_preact = torch.matmul(x, w1) + b1 # 입력층\n",
    "h = torch.nn.functional.relu(h_preact) # 은닉층\n",
    "y = torch.matmul(h, w2) + b2 # 출력층"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "18fdde47",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "tensor([ 9,  2, -6])"
      ]
     },
     "execution_count": 28,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "h_preact"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "fe918c1a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "tensor([9, 2, 0])"
      ]
     },
     "execution_count": 29,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "h"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "fe48b66d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "tensor([-8, 12])"
      ]
     },
     "execution_count": 30,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "y"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "360bd4c8",
   "metadata": {},
   "source": [
    "레이어 정규화 예시\n",
    "\n",
    "입력모양: 배치크기(2) x 피처의 차원수(3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "8762ba34",
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "input = torch.tensor([[1.0, 2.0, 3.0], [1.0, 1.0, 1.0]]) # 배치 2; 피처의 차원수 3\n",
    "m = torch.nn.LayerNorm(input.shape[-1]) # 레이어 정규화 수행\n",
    "output = m(input)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "8fa00e08",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "tensor([[-1.2247,  0.0000,  1.2247],\n",
       "        [ 0.0000,  0.0000,  0.0000]], grad_fn=<NativeLayerNormBackward0>)"
      ]
     },
     "execution_count": 34,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "output"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e0aa5587",
   "metadata": {},
   "source": [
    "감마 (weight), 바이어스 (bias)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "84a34440",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Parameter containing:\n",
       "tensor([1., 1., 1.], requires_grad=True)"
      ]
     },
     "execution_count": 35,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "m.weight"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "bfe2015f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Parameter containing:\n",
       "tensor([0., 0., 0.], requires_grad=True)"
      ]
     },
     "execution_count": 36,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "m.bias"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9c9e80ef",
   "metadata": {},
   "source": [
    "드롭아웃 구현"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "c270186b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "m = torch.nn.Dropout(p=0.2) # 드롭아웃 수행비율 평균적으로 20% 만듦\n",
    "input = torch.randn(1, 10)\n",
    "output = m(input)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "ebe57754",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Dropout(p=0.2, inplace=False)"
      ]
     },
     "execution_count": 38,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "m"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "7ebba528",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "tensor([[ 0.7341, -1.0007, -0.9627,  1.1245, -0.9849, -0.3998, -0.2957, -0.1473,\n",
       "         -0.4646,  0.8293]])"
      ]
     },
     "execution_count": 39,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "input"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "c5e87af1",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "tensor([[ 0.9176, -1.2508, -1.2033,  0.0000, -1.2311, -0.4997, -0.3696, -0.0000,\n",
       "         -0.5807,  0.0000]])"
      ]
     },
     "execution_count": 40,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "output"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a667685b",
   "metadata": {},
   "source": [
    "-> 위에서 보듯, 8번째, 10번째가 0으로 대치됨 (드롭아웃 적용)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a749da9b",
   "metadata": {},
   "source": [
    "아담옵티마이저 구현"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "30101ca1",
   "metadata": {},
   "outputs": [
    {
     "ename": "AttributeError",
     "evalue": "'Tensor' object has no attribute 'parameters'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/m_/0wydsstd3blg19r7_0zhqlmh0000gn/T/ipykernel_8173/2229282177.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mtorch\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0moptim\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mAdam\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mmodel\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0moutput\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0moptimizer\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mAdam\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmodel\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mparameters\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlr\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mmodel\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlearning_rate\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m: 'Tensor' object has no attribute 'parameters'"
     ]
    }
   ],
   "source": [
    "from torch.optim import Adam\n",
    "model = output\n",
    "optimizer = Adam(model.parameters(), lr=model.learning_rate)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "df3349fb",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "GPT_BERT_book",
   "language": "python",
   "name": "gpt_bert_book"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
